"""jsonb

Revision ID: 3b14f1d93836
Revises: bf56b3582149
Create Date: 2025-11-25 09:09:53.077080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b14f1d93836'
down_revision: Union[str, None] = 'bf56b3582149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_versions', sa.Column('original_uri', sa.String(length=500), nullable=True))
    op.drop_column('regulation_versions', 'original_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_versions', sa.Column('original_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('regulation_versions', 'original_uri')
    # ### end Alembic commands ###
