"""Initial migration

Revision ID: bf56b3582149
Revises: 
Create Date: 2025-11-11 15:14:28.626877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf56b3582149'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('admin_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('countries',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('crawl_jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('schedule_rule', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('glossary_terms',
    sa.Column('glossary_term_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_key', sa.String(length=100), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('synonyms', sa.String(length=500), nullable=True),
    sa.Column('mistranslations', sa.String(length=500), nullable=True),
    sa.Column('legal_terms', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('glossary_term_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_category', sa.Enum('COMBUSTIBLE', 'HTP', 'E_CIGARETTE', name='productcategoryenum'), nullable=False),
    sa.Column('manufactured_at', sa.DateTime(), nullable=True),
    sa.Column('nicotin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tarr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('menthol', sa.Boolean(), nullable=True),
    sa.Column('incense', sa.Boolean(), nullable=True),
    sa.Column('battery', sa.String(length=50), nullable=True),
    sa.Column('label_size', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('security_auth', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('crawl_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('product_export_countries',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'country_code')
    )
    op.create_table('regulations',
    sa.Column('regulation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('proclaimed_date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('regulation_id')
    )
    op.create_table('regulation_versions',
    sa.Column('regulation_version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=True),
    sa.Column('hash_value', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.regulation_id'], ),
    sa.PrimaryKeyConstraint('regulation_version_id')
    )
    op.create_table('regulation_change_history',
    sa.Column('change_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regulation_version_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('NONE', 'APPEND', 'NEW', 'REPEAL', name='changetypeenum'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.regulation_version_id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_table('regulation_translations',
    sa.Column('translation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regulation_version_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('glossary_term_id', sa.Integer(), nullable=True),
    sa.Column('translation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['glossary_term_id'], ['glossary_terms.glossary_term_id'], ),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.regulation_version_id'], ),
    sa.PrimaryKeyConstraint('translation_id')
    )
    op.create_table('impact_scores',
    sa.Column('impact_score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('impact_score', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevelenum'), nullable=False),
    sa.Column('evaluation_detail', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['regulation_translations.translation_id'], ),
    sa.PrimaryKeyConstraint('impact_score_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['regulation_change_history.change_id'], ),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['regulation_translations.translation_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('regulation_change_keynotes',
    sa.Column('keynote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('regulation_version_id', sa.Integer(), nullable=False),
    sa.Column('impact_score_id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('regulation_type', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ),
    sa.ForeignKeyConstraint(['impact_score_id'], ['impact_scores.impact_score_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.regulation_version_id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['regulation_translations.translation_id'], ),
    sa.PrimaryKeyConstraint('keynote_id')
    )
    op.create_table('report_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('regulation_version_id', sa.Integer(), nullable=False),
    sa.Column('impact_score_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impact_score_id'], ['impact_scores.impact_score_id'], ),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.regulation_version_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('report_summaries',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('impact_score_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['impact_score_id'], ['impact_scores.impact_score_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_summaries')
    op.drop_table('report_items')
    op.drop_table('regulation_change_keynotes')
    op.drop_table('reports')
    op.drop_table('impact_scores')
    op.drop_table('regulation_translations')
    op.drop_table('regulation_change_history')
    op.drop_table('regulation_versions')
    op.drop_table('regulations')
    op.drop_table('product_export_countries')
    op.drop_table('crawl_logs')
    op.drop_table('products')
    op.drop_table('glossary_terms')
    op.drop_table('data_sources')
    op.drop_table('crawl_jobs')
    op.drop_table('countries')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
