"""jsonb

Revision ID: caa88c203a42
Revises: 3b14f1d93836
Create Date: 2025-11-25 10:33:59.319875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'caa88c203a42'
down_revision: Union[str, None] = '3b14f1d93836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regulation_change_history', 'change_type',
               existing_type=postgresql.ENUM('NONE', 'APPEND', 'NEW', 'REPEAL', name='changetypeenum'),
               nullable=True)
    op.create_index(op.f('ix_regulation_change_history_change_id'), 'regulation_change_history', ['change_id'], unique=False)
    op.add_column('regulation_change_keynotes', sa.Column('keynote_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_regulation_change_keynotes_keynote_id'), 'regulation_change_keynotes', ['keynote_id'], unique=False)
    op.drop_constraint(op.f('regulation_change_keynotes_impact_score_id_fkey'), 'regulation_change_keynotes', type_='foreignkey')
    op.drop_constraint(op.f('regulation_change_keynotes_regulation_version_id_fkey'), 'regulation_change_keynotes', type_='foreignkey')
    op.drop_constraint(op.f('regulation_change_keynotes_translation_id_fkey'), 'regulation_change_keynotes', type_='foreignkey')
    op.drop_constraint(op.f('regulation_change_keynotes_country_code_fkey'), 'regulation_change_keynotes', type_='foreignkey')
    op.drop_constraint(op.f('regulation_change_keynotes_product_id_fkey'), 'regulation_change_keynotes', type_='foreignkey')
    op.drop_column('regulation_change_keynotes', 'product_id')
    op.drop_column('regulation_change_keynotes', 'translation_id')
    op.drop_column('regulation_change_keynotes', 'regulation_version_id')
    op.drop_column('regulation_change_keynotes', 'impact_score_id')
    op.drop_column('regulation_change_keynotes', 'title')
    op.drop_column('regulation_change_keynotes', 'country_code')
    op.drop_column('regulation_change_keynotes', 'regulation_type')
    op.alter_column('regulation_translations', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('regulation_translations', 'translated_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('regulation_translations', 'translation_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_regulation_translations_translation_id'), 'regulation_translations', ['translation_id'], unique=False)
    op.alter_column('regulation_versions', 'hash_value',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.create_index(op.f('ix_regulation_versions_regulation_version_id'), 'regulation_versions', ['regulation_version_id'], unique=False)
    op.alter_column('regulations', 'external_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('regulations', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('regulations', 'proclaimed_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('regulations', 'effective_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('regulations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_regulations_regulation_id'), 'regulations', ['regulation_id'], unique=False)
    op.alter_column('report_items', 'regulation_version_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('report_items', 'impact_score_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('report_items', 'order_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_report_items_item_id'), 'report_items', ['item_id'], unique=False)
    op.alter_column('report_summaries', 'summary_text',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_report_summaries_summary_id'), 'report_summaries', ['summary_id'], unique=False)
    op.drop_constraint(op.f('report_summaries_impact_score_id_fkey'), 'report_summaries', type_='foreignkey')
    op.drop_constraint(op.f('report_summaries_report_id_fkey'), 'report_summaries', type_='foreignkey')
    op.drop_column('report_summaries', 'impact_score_id')
    op.drop_column('report_summaries', 'report_id')
    op.alter_column('reports', 'created_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('reports', 'change_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reports', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.alter_column('reports', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reports', 'change_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reports', 'created_reason',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('report_summaries', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('report_summaries', sa.Column('impact_score_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('report_summaries_report_id_fkey'), 'report_summaries', 'reports', ['report_id'], ['report_id'])
    op.create_foreign_key(op.f('report_summaries_impact_score_id_fkey'), 'report_summaries', 'impact_scores', ['impact_score_id'], ['impact_score_id'])
    op.drop_index(op.f('ix_report_summaries_summary_id'), table_name='report_summaries')
    op.alter_column('report_summaries', 'summary_text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_report_items_item_id'), table_name='report_items')
    op.alter_column('report_items', 'order_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('report_items', 'impact_score_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('report_items', 'regulation_version_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_regulations_regulation_id'), table_name='regulations')
    op.alter_column('regulations', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('regulations', 'effective_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('regulations', 'proclaimed_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('regulations', 'title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('regulations', 'external_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_regulation_versions_regulation_version_id'), table_name='regulation_versions')
    op.alter_column('regulation_versions', 'hash_value',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_index(op.f('ix_regulation_translations_translation_id'), table_name='regulation_translations')
    op.alter_column('regulation_translations', 'translation_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('regulation_translations', 'translated_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('regulation_translations', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('regulation_change_keynotes', sa.Column('regulation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('regulation_change_keynotes', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('regulation_change_keynotes', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('regulation_change_keynotes', sa.Column('impact_score_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('regulation_change_keynotes', sa.Column('regulation_version_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('regulation_change_keynotes', sa.Column('translation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('regulation_change_keynotes', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('regulation_change_keynotes_product_id_fkey'), 'regulation_change_keynotes', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key(op.f('regulation_change_keynotes_country_code_fkey'), 'regulation_change_keynotes', 'countries', ['country_code'], ['country_code'])
    op.create_foreign_key(op.f('regulation_change_keynotes_translation_id_fkey'), 'regulation_change_keynotes', 'regulation_translations', ['translation_id'], ['translation_id'])
    op.create_foreign_key(op.f('regulation_change_keynotes_regulation_version_id_fkey'), 'regulation_change_keynotes', 'regulation_versions', ['regulation_version_id'], ['regulation_version_id'])
    op.create_foreign_key(op.f('regulation_change_keynotes_impact_score_id_fkey'), 'regulation_change_keynotes', 'impact_scores', ['impact_score_id'], ['impact_score_id'])
    op.drop_index(op.f('ix_regulation_change_keynotes_keynote_id'), table_name='regulation_change_keynotes')
    op.drop_column('regulation_change_keynotes', 'keynote_text')
    op.drop_index(op.f('ix_regulation_change_history_change_id'), table_name='regulation_change_history')
    op.alter_column('regulation_change_history', 'change_type',
               existing_type=postgresql.ENUM('NONE', 'APPEND', 'NEW', 'REPEAL', name='changetypeenum'),
               nullable=False)
    # ### end Alembic commands ###
