-- =========================================
-- ENUM TYPES (idempotent)
-- =========================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'product_category_enum') THEN
    CREATE TYPE product_category_enum AS ENUM ('combustible', 'htp', 'e_cigarette');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'risk_level_enum') THEN
    CREATE TYPE risk_level_enum AS ENUM ('LOW', 'MEDIUM', 'HIGH');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'change_type_enum') THEN
    CREATE TYPE change_type_enum AS ENUM ('none', 'append', 'new', 'repeal');
  END IF;
END$$;
-- =========================================
-- TABLES
-- =========================================

-- Admin users
CREATE TABLE IF NOT EXISTS admin_users (
  admin_user_id   integer PRIMARY KEY,
  username        varchar(50) UNIQUE NOT NULL,
  password        varchar(50) NOT NULL
);

-- Countries
CREATE TABLE IF NOT EXISTS countries (
  country_code    char(2) PRIMARY KEY,    -- KR, US
  country_name    varchar(100)
);

-- Products
CREATE TABLE IF NOT EXISTS products ( 
	product_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY key,
	product_name varchar(50), 
	product_category product_category_enum, 
	manufactured_at timestamp DEFAULT now(), 
	nicotin varchar(20) not null, 
	tarr varchar(20) not null, 
	menthol boolean,
	incense boolean,
	battery varchar(20) not null, 
	label_size varchar(20),
	image text,
	Security_auth boolean,
	Revenue int
);
-- Product export countries (scope for map)
CREATE TABLE IF NOT EXISTS product_export_countries (
  product_id      integer NOT NULL,
  country_code    char(2) NOT NULL,
  note            varchar(200),
  CONSTRAINT product_export_countries_pk PRIMARY KEY (product_id, country_code)
);

-- Glossary terms
CREATE TABLE IF NOT EXISTS glossary_terms (
  glossary_term_id    uuid PRIMARY KEY,
  canonical_key       varchar(100),     -- e.g., nicotine_limit
  language_code       varchar(10),      -- KO, EN, RU ...
  definition          text,
  synonyms            varchar(300),     -- comma-separated
  mistranslations     varchar(300),     -- optional, translation caveats
  legal_terms         varchar(300),     -- original/local legal term
  created_at          timestamp DEFAULT now(),
  updated_at          timestamp,
  CONSTRAINT uq_glossary_canonical_lang UNIQUE (canonical_key, language_code)
);

-- Data sources
CREATE TABLE IF NOT EXISTS data_sources (
  source_id       integer PRIMARY KEY,
  source_name     varchar(150),
  url             varchar(500),
  source_type     varchar(20)           -- rss, html, api, pdf
);

-- Crawl jobs
CREATE TABLE IF NOT EXISTS crawl_jobs (
  job_id          integer PRIMARY KEY,
  job_name        varchar(150),
  schedule_rule   varchar(100),         -- cron/rate
  is_active       boolean DEFAULT true
);

-- Crawl logs
CREATE TABLE IF NOT EXISTS crawl_logs (
  log_id          integer PRIMARY KEY,
  job_id          integer,
  source_id       integer,
  status          varchar(10),          -- success, failed
  created_at      timestamp DEFAULT now()
);

-- Regulations
CREATE TABLE IF NOT EXISTS regulations (
  regulation_id   integer PRIMARY KEY,
  source_id       integer NOT NULL,
  country_code    char(2) NOT NULL,
  external_id     varchar(200),
  title           varchar(100),
  proclaimed_date date,
  effective_date  date,
  language        varchar(10),
  status          varchar(20),          -- active, repealed
  created_at      timestamp DEFAULT now()
  -- Note: content changes are versioned by regulation_versions
);

-- Regulation versions
CREATE TABLE IF NOT EXISTS regulation_versions (
  regulation_version_id  integer PRIMARY KEY,
  regulation_id          integer NOT NULL,
  version_number         integer NOT NULL,
  original_uri           varchar(500),
  hash_value             varchar(128),
  created_at             timestamp DEFAULT now()
);

-- Change keynotes (product/country-scoped TOP items)
CREATE TABLE IF NOT EXISTS regulation_change_keynotes (
  keynote_id             integer PRIMARY KEY,
  product_id             integer NOT NULL,
  country_code           char(2) NOT NULL,
  regulation_version_id  integer NOT NULL,
  impact_score_id        integer NOT NULL,
  translation_id         integer NOT NULL,
  title                  varchar(100),
  regulation_type        varchar(50),
  generated_at           timestamp DEFAULT now()
);

-- Regulation translations
CREATE TABLE IF NOT EXISTS regulation_translations (
  translation_id         integer PRIMARY KEY,
  regulation_version_id  integer NOT NULL,
  language_code          varchar(10),      -- KO, EN...
  translated_text        text,
  glossary_term_id       uuid,
  translation_status     varchar(20),
  created_at             timestamp DEFAULT now(),
  CONSTRAINT uq_regulation_trans_lang UNIQUE (regulation_version_id, language_code)
);

-- Regulation change history
CREATE TABLE IF NOT EXISTS regulation_change_history (
  change_id              integer PRIMARY KEY,
  regulation_version_id  integer NOT NULL,
  change_type            change_type_enum, -- none, append, new, repeal
  change_summary         text,
  detected_at            timestamp DEFAULT now()
);

-- Impact scores (per product)
CREATE TABLE IF NOT EXISTS impact_scores (
  impact_score_id    integer PRIMARY KEY,
  translation_id     integer NOT NULL,
  product_id         integer NOT NULL,
  impact_score       numeric(4,3),        -- 0.000 ~ 1.000
  risk_level         risk_level_enum,     -- low/medium/high
  evaluation_detail  text,                -- rationale
  evaluated_at       timestamp DEFAULT now(),
  CONSTRAINT uq_impact_translation_product UNIQUE (translation_id, product_id)
);

-- Reports
CREATE TABLE IF NOT EXISTS reports (
  report_id        integer PRIMARY KEY,
  created_reason   varchar(30),           -- recommend 'change_detected'
  created_at       timestamp DEFAULT now(),
  file_path        varchar(500),
  translation_id   integer NOT NULL,
  change_id        integer,
  product_id       integer,
  country_code     char(2) NOT NULL
);

-- Report items
CREATE TABLE IF NOT EXISTS report_items (
  item_id               integer PRIMARY KEY,
  report_id             integer NOT NULL,
  regulation_version_id integer,
  impact_score_id       integer,
  order_no              integer GENERATED BY DEFAULT AS IDENTITY
);

-- Report summaries (3-line summary etc.)
CREATE TABLE IF NOT EXISTS report_summaries (
  summary_id       integer PRIMARY KEY,
  report_id        integer NOT NULL,
  impact_score_id  integer NOT NULL,
  summary_text     varchar(300) NOT NULL,
  created_at       timestamp DEFAULT now()
);

-- =========================================
-- FOREIGN KEYS
-- =========================================

-- product_export_countries
ALTER TABLE product_export_countries
  ADD CONSTRAINT fk_pec_product  FOREIGN KEY (product_id)   REFERENCES products(product_id),
  ADD CONSTRAINT fk_pec_country  FOREIGN KEY (country_code) REFERENCES countries(country_code);

-- crawl_logs
ALTER TABLE crawl_logs
  ADD CONSTRAINT fk_crawl_logs_job    FOREIGN KEY (job_id)    REFERENCES crawl_jobs(job_id),
  ADD CONSTRAINT fk_crawl_logs_source FOREIGN KEY (source_id) REFERENCES data_sources(source_id);

-- regulations
ALTER TABLE regulations
  ADD CONSTRAINT fk_regulations_source  FOREIGN KEY (source_id)   REFERENCES data_sources(source_id),
  ADD CONSTRAINT fk_regulations_country FOREIGN KEY (country_code) REFERENCES countries(country_code);

-- regulation_versions
ALTER TABLE regulation_versions
  ADD CONSTRAINT fk_reg_version_reg FOREIGN KEY (regulation_id) REFERENCES regulations(regulation_id);

-- regulation_translations
ALTER TABLE regulation_translations
  ADD CONSTRAINT fk_reg_trans_version  FOREIGN KEY (regulation_version_id) REFERENCES regulation_versions(regulation_version_id),
  ADD CONSTRAINT fk_reg_trans_glossary FOREIGN KEY (glossary_term_id)      REFERENCES glossary_terms(glossary_term_id);

-- regulation_change_history
ALTER TABLE regulation_change_history
  ADD CONSTRAINT fk_change_hist_version FOREIGN KEY (regulation_version_id) REFERENCES regulation_versions(regulation_version_id);

-- impact_scores
ALTER TABLE impact_scores
  ADD CONSTRAINT fk_impact_translation FOREIGN KEY (translation_id) REFERENCES regulation_translations(translation_id),
  ADD CONSTRAINT fk_impact_product     FOREIGN KEY (product_id)     REFERENCES products(product_id);

-- regulation_change_keynotes
ALTER TABLE regulation_change_keynotes
  ADD CONSTRAINT fk_keynotes_product       FOREIGN KEY (product_id)            REFERENCES products(product_id),
  ADD CONSTRAINT fk_keynotes_country       FOREIGN KEY (country_code)          REFERENCES countries(country_code),
  ADD CONSTRAINT fk_keynotes_version       FOREIGN KEY (regulation_version_id) REFERENCES regulation_versions(regulation_version_id),
  ADD CONSTRAINT fk_keynotes_impact        FOREIGN KEY (impact_score_id)       REFERENCES impact_scores(impact_score_id),
  ADD CONSTRAINT fk_keynotes_translation   FOREIGN KEY (translation_id)        REFERENCES regulation_translations(translation_id);

-- reports
ALTER TABLE reports
  ADD CONSTRAINT fk_reports_translation FOREIGN KEY (translation_id) REFERENCES regulation_translations(translation_id),
  ADD CONSTRAINT fk_reports_change      FOREIGN KEY (change_id)      REFERENCES regulation_change_history(change_id),
  ADD CONSTRAINT fk_reports_product     FOREIGN KEY (product_id)     REFERENCES products(product_id),
  ADD CONSTRAINT fk_reports_country     FOREIGN KEY (country_code)   REFERENCES countries(country_code);

-- report_items
ALTER TABLE report_items
  ADD CONSTRAINT fk_report_items_report    FOREIGN KEY (report_id)             REFERENCES reports(report_id),
  ADD CONSTRAINT fk_report_items_version   FOREIGN KEY (regulation_version_id) REFERENCES regulation_versions(regulation_version_id),
  ADD CONSTRAINT fk_report_items_impact    FOREIGN KEY (impact_score_id)       REFERENCES impact_scores(impact_score_id);

-- report_summaries
ALTER TABLE report_summaries
  ADD CONSTRAINT fk_report_summaries_report FOREIGN KEY (report_id)      REFERENCES reports(report_id),
  ADD CONSTRAINT fk_report_summaries_impact FOREIGN KEY (impact_score_id) REFERENCES impact_scores(impact_score_id);

-- =========================================
-- (Optional) Helpful indexes — 주석 해제하여 사용
-- =========================================
-- CREATE INDEX IF NOT EXISTS idx_regulations_country ON regulations(country_code);
-- CREATE INDEX IF NOT EXISTS idx_reg_versions_reg     ON regulation_versions(regulation_id);
-- CREATE INDEX IF NOT EXISTS idx_keynotes_prod_ctry   ON regulation_change_keynotes(product_id, country_code);
-- CREATE INDEX IF NOT EXISTS idx_impact_product       ON impact_scores(product_id);
-- CREATE INDEX IF NOT EXISTS idx_reports_country      ON reports(country_code);
